//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public int Id_Passenger { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Id_Tour { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
